// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI / migrations use a DIRECT (non-pooled) connection — PgBouncer
    // doesn't support the advisory locks migrations need. The app runtime still
    // uses the pooled DATABASE_URL (see lib/db/prisma.ts). Falls back to pooled
    // if DIRECT_URL is unset.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
